apiVersion: v1
kind: Service
metadata:
  name: vision-pipeline
  namespace: geoint-vision
spec:
  type: NodePort
  selector:
    app: vision-pipeline
  ports:
    - name: frontend
      port: 8081
      targetPort: 8081
      nodePort: 30081
    - name: api
      port: 8082
      targetPort: 8082
      nodePort: 30082
