apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - demo1-vision-pipeline/namespace.yaml
  - demo1-vision-pipeline/deployment.yaml
  - demo1-vision-pipeline/service.yaml
  - demo4-ai-assistant/namespace.yaml
  - demo4-ai-assistant/deployment.yaml
  - demo4-ai-assistant/service.yaml
