apiVersion: v1
kind: Service
metadata:
  name: analyst-assistant
  namespace: geoint-assistant
spec:
  type: NodePort
  selector:
    app: analyst-assistant
  ports:
    - name: chat-ui
      port: 8086
      targetPort: 8086
      nodePort: 30086
    - name: chat-api
      port: 8087
      targetPort: 8087
      nodePort: 30087
